# Os specific settings.
if-shell -b '[ "$(uname -s)" = "Linux" ]' " \
  set -g default-shell /usr/bin/zsh; \
  set -g status-position top; \
"
if-shell -b '[ "$(uname -s)" = "Darwin" ]' " \
  set -g default-shell $(which zsh); \
  set -g status-position bottom; \
"

set-window-option -g mode-keys emacs
set-option -g status-keys emacs

# Enable truecolors.
set -g default-terminal "xterm-256color"
set -g terminal-overrides ",xterm-256color:Tc"

# Edit tmux config and load it when done.
bind C-r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'
bind C-h new-window 'htop'
bind C-p new-window 'ping 8.8.8.8'
bind C-d new-window 'dig google.com; sleep 4'
bind C-e new-window -n '~/.tmux.conf' 'emacsclient -a "" -c -t ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display "~/.tmux.conf sourced"'
bind C-n command-prompt -p new-session 'new-session -A -s %%'
bind C-s set synchronize-panes

# Auto renumber window ids.
set-option -g renumber-windows on

# Window titles.
set-option -g set-titles on
set-window-option -g automatic-rename off
set-option -g allow-rename on

bind -n Home choose-tree
# Cycling windows.
bind -n S-right next
bind -n S-left prev
# Cycling sessions.
bind -n S-Up switch-client -p
bind -n S-Down switch-client -n

# Status bar.
set-option -g visual-activity on
set-window-option -g monitor-activity on

# Clock.
set-window-option -g clock-mode-style 12

bind-key = select-layout main-vertical
bind < resize-pane -L 25
bind > resize-pane -R 25

# Faster statusbar refresh.
set -g status-interval 15

# Messages should linger for more than 750ms.
set-option -g display-time 2500

setw -g aggressive-resize on

# Start window indexes at 1 instead of 0.
set -g base-index 1
set-window-option -g pane-base-index 1

# Mouse support: scroll, select panes, resize panes, select windows.
set -g mouse on

# Default to current dir for new panes/windows.
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -g history-limit 50000

# Plugins (managed by tpm).
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'

run '~/.tmux/plugins/tpm/tpm'
