[ -n "${ZPROF}" ] && zmodload zsh/zprof

export TMUX_TZ=$(date +%Z)
export COLORTERM=truecolor
# User config.

source $HOME/.aliases

# Oh-my-zsh config.

# Disable completion security check as it is too slow. Don't manually add any completions before checking them.
ZSH_DISABLE_COMPFIX=true


# Enable shared history so we can reference history between terms.
setopt share_history
# Save each command in history to make sure we don't loose it.
setopt inc_append_history

ZSH_THEME="powerlevel10k/powerlevel10k"
CASE_SENSITIVE="true"

# Load oh-my-zsh.
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Detect SSH session and set SSH agent-forwarding accordingly
if [[ -n "$SSH_CLIENT" || -n "$SSH_CONNECTION" ]]; then
  zstyle ':omz:plugins:ssh-agent' agent-forwarding on
fi

# Load files for  functions
fpath=( ~/.zsh_functions "${fpath[@]}" )

source $HOME/.autoload

# Load the private config if set.
[ -f ~/.zshrc_priv_config ] && source ~/.zshrc_priv_confi

export NVM_DIR="$HOME/.nvm"

zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript # Already has node, npm, npx, pnpm, yarn, and corepack
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading

connectaws () {
  eval "$(assumerole -f env $1)"
}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If the ssh agent socket is not set or expired, reload it.
if [ -z "$SSH_AUTH_SOCK" ] || [ ! -S "$SSH_AUTH_SOCK" ]; then
  rl
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# load plugins here. Ideally this should not produce console output.
eval "$(sheldon source)"

# Tell git to use the current tty for gpg passphrase prompt (needs to be at the end so the tty is within tmux, not out).
export GPG_TTY=$(tty)
# Stop profiling
[ -n "${ZPROF}" ] && zprof
